language: node_js
node_js:
  - "10.13.0"

services:
  - docker

before_script:
  - sudo service mysql stop
  - docker pull mariadb:10.3.15
  - docker run --name mariadb -e MYSQL_ROOT_PASSWORD=password -e MYSQL_DATABASE=haimich -e MYSQL_USER=haimich -e MYSQL_PASSWORD=haimich -p 3306:3306 -d mariadb:10.3.15
  - mysql -e 'CREATE DATABASE IF NOT EXISTS haimich;'
  - npm run db:rebuild