version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.13.0
      - image: circleci/mariadb:10.3.15
        command: [--name mariadb, -e MYSQL_ROOT_PASSWORD=password, -e MYSQL_DATABASE=haimich, -e MYSQL_USER=haimich, -e MYSQL_PASSWORD=haimich, -p 3306:3306]

    working_directory: ~/repo

    steps:
      - checkout

      - run: docker run --name mariadb -e MYSQL_ROOT_PASSWORD=password -e MYSQL_DATABASE=haimich -e MYSQL_USER=haimich -e MYSQL_PASSWORD=haimich -p 3306:3306 -d mariadb:10.3.15

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: npm test